package org.example.app.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * PUBLIC_INTERFACE
 * Note entity representing a user's note.
 * Fields:
 *  - id: autogenerated primary key
 *  - title: note title
 *  - content: note body
 *  - categoryId: foreign key to Category (nullable)
 *  - tags: comma-separated tags
 *  - updatedAt: millis timestamp
 */
@Entity(tableName = "notes")
data class Note(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val content: String,
    val categoryId: Long?,
    val tags: String,
    val updatedAt: Long
)
